export const DUMMY_ANNOTATION_TASKS = [
  {
    id: 1,
    timestamp: 1680000000000,
    status: "In Progress",
    images: [
      {
        id: 1443,
        specimenId: "UNZ003",
        imageUrl: "https://api.vectorcam.org/specimens/16/images/18",
        morphSpecies: undefined,
        morphSex: undefined,
        morphAbdomenStatus: undefined,
        annotationStatus: "UNANNOTATED",
        notes: undefined,
      },
      {
        id: 1444,
        specimenId: "UNZ004",
        imageUrl: "https://api.vectorcam.org/specimens/16/images/18",
        morphSpecies: "Anopheles gambiae",
        morphSex: "Male",
        morphAbdomenStatus: undefined,
        annotationStatus: "ANNOTATED",
        notes: undefined,
      },
      {
        id: 1445,
        specimenId: "UNZ005",
        imageUrl: "https://api.vectorcam.org/specimens/16/images/18",
        morphSpecies: undefined,
        morphSex: undefined,
        morphAbdomenStatus: undefined,
        annotationStatus: "FLAGGED",
        notes: "Requires further review",
      },
    ],
  },
  {
    id: 2,
    district: "Mukono",
    timestamp: 1682000000000,
    status: "In Progress",
    images: [
      {
        id: 1446,
        specimenId: "UNZ005",
        imageUrl: "https://api.vectorcam.org/specimens/16/images/18",
        morphSpecies: undefined,
        morphSex: undefined,
        morphAbdomenStatus: undefined,
        annotationStatus: "FLAGGED",
        notes: "Requires further review",
      },
      {
        id: 1447,
        specimenId: "UNZ005",
        imageUrl: "https://api.vectorcam.org/specimens/16/images/18",
        morphSpecies: undefined,
        morphSex: undefined,
        morphAbdomenStatus: undefined,
        annotationStatus: "ANNOTATED",
        notes: "Requires further review",
      },
    ],
  },
];
